---
# This playbook contains common plays that will be run on all nodes.

- name: Install common dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - xfce4
    - xfce4-goodies
    - language-pack-ja-base
    - language-pack-ja
    # - ibus-mozc 
    - fonts-ipafont
    - fonts-ipaexfont
    - manpages-ja #なくても良い
    - manpages-ja-dev
    - tightvncserver

- name: locale
  shell: |
    sudo localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
    # sudo localectl set-locale LANG=en_US.UTF-8 LANGUAGE="en_US.UTF-8"

- name: add repository vivaldi
  shell: |
    wget -qO- https://repo.vivaldi.com/archive/linux_signing_key.pub | sudo apt-key add -
    sudo add-apt-repository 'deb https://repo.vivaldi.com/archive/deb/ stable main'

- name: Install common dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - vivaldi-stable

	# chrome は落としてくるか
	#dpkg -i chrome_path