# updateしておく
# systemtapでカーネルversionを合わせるため、再起動が必要かも
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install monitoring tools
  yum: name={{ item }} state=installed
    name:
    - openscap-scanner #脆弱性スキャン
    - scap-security-guide
    - openscap-utils #oscap-docker
    - audit #システムコール等の監視
    - aide #改竄検知
    - systemtap
    - systemtap-runtime


# sshd_configにALLOW_SSH_ROOT_USER=noを書き込んでおく
- name: Install rkhunter with repo epel
  yum:
    name: 
      - rkhunter
    enablerepo: "epel"
    state: present

- name: systemtap
  command: yum --disablerepo=* --enablerepo=base-debuginfo \
     -y install kernel-devel-$(uname -r) kernel-debuginfo-$(uname -r) kernel-debuginfo-common-$(uname -m)-$(uname -r)

- name: fluentd
  command: curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh | sh

