- name: Create a 4096-bit SSH key for user developer
  user:
    name: "{{creat_user}}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    # groups: sudo
    password: "{{ 'pass'|password_hash('sha512') }}"
    ssh_key_passphrase: "{{key_passphrase}}"
    update_password: always

- name: to authorized_keys
  become_user: "{{creat_user}}"
  shell: |
    cat /home/{{creat_user}}/.ssh/id_rsa.pub > /home/{{creat_user}}/.ssh/authorized_keys

- name: download and setup nodejs source
  fetch:
    src: /home/{{creat_user}}/.ssh/id_rsa
    dest: ~/.ssh/download/