# - name: uninstall php all
#   command: yum remove php-*

- name: Install package with multiple repos enabled
  yum:
    name: 
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - yum-utils
    state: present
    
- name: Install php package with repo
  yum:
    name: 
      - php
      - php-devel
      - php-fpm
      - php-gd
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-pdo
      - php-xml
      - php-zip
      - php-pecl-zip
      - php-opcache
      - php-pecl-apcu
    enablerepo: "remi,remi-php73"
    state: installed